# Generated by Django 5.2 on 2026-04-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='power_rating_watts',
            field=models.FloatField(default=60.0),
        ),
    ]
