# Generated by Django 5.2 on 2026-04-29 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_device_power_rating_watts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUsageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('energy_consumed_kwh', models.FloatField(default=0.0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='Home.device')),
            ],
        ),
    ]
