# Generated by Django 5.2 on 2026-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_deviceusagesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('consumption_kwh', models.FloatField()),
                ('temperature_c', models.FloatField(default=25.0)),
                ('humidity_pct', models.FloatField(default=50.0)),
                ('occupancy', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
